{"version":3,"file":"useAuthError.js","sourceRoot":"","sources":["../../../src/hooks/useAuthError.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,cAAc,EAAE,MAAM,+BAA+B,CAAC;AAI/D;;;;;;;;;;;;;;;GAeG;AACH,MAAM,UAAU,YAAY;IAC1B,MAAM,EAAE,QAAQ,EAAE,GAAG,cAAc,EAAE,CAAC;IACtC,IAAI,OAAO,IAAI,QAAQ,EAAE,CAAC;QACxB,OAAO,QAAQ,CAAC,KAAK,CAAC;IACxB,CAAC;IAED,OAAO,SAAS,CAAC;AACnB,CAAC","sourcesContent":["import { useAuthContext } from \"../components/auth/context.js\";\n\nexport type UseAuthErrorResult = Error | undefined;\n\n/**\n * Returns the error returned from the current auth step, if it exists\n *\n * @returns {UseAuthErrorResult} the current Error object\n *\n * @example\n * ```tsx twoslash\n * import { useAuthError } from \"@account-kit/react\";\n *\n * const error = useAuthError();\n *\n * if (error) {\n *  console.error(\"Error occurred during auth step\", error);\n * }\n * ```\n */\nexport function useAuthError(): UseAuthErrorResult {\n  const { authStep } = useAuthContext();\n  if (\"error\" in authStep) {\n    return authStep.error;\n  }\n\n  return undefined;\n}\n"]}